In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from scipy.stats import ttest_ind
from scipy import stats
import scipy.stats as st

In [3]:
disease_data = pd.read_csv("data/outbreaks.csv")

In [4]:
disease_data

,Year,Month,State,Location,Food,Ingredient,Species,Serotype/Genotype,Status,Illnesses,Hospitalizations,Fatalities
0,1998,January,California,Restaurant,NaN,NaN,NaN,NaN,NaN,20,0.0,0.0
1,1998,January,California,NaN,Custard,NaN,NaN,NaN,NaN,112,0.0,0.0
2,1998,January,California,Restaurant,NaN,NaN,NaN,NaN,NaN,35,0.0,0.0
3,1998,January,California,Restaurant,"Fish, Ahi",NaN,Scombroid toxin,NaN,Confirmed,4,0.0,0.0
4,1998,January,California,Private Home/Residence,"Lasagna, Unspecified; Eggs, Other",NaN,Salmonella enterica,Enteritidis,Confirmed,26,3.0,0.0
5,1998,January,California,Restaurant,NaN,NaN,Shigella boydii,NaN,Confirmed,25,3.0,0.0
6,1998,January,California,Restaurant,NaN,NaN,NaN,NaN,NaN,8,0.0,0.0
7,1998,January,California,Restaurant,"Stuffing, Unspecified; Sandwich, Turkey",NaN,Salmonella enterica,Enteritidis,Confirmed,4,3.0,0.0
8,1998,January,Colorado,Restaurant,"Salad, Unspecified",NaN,Virus,NaN,Suspected,21,NaN,NaN
9,1998,January,Colorado,Restaurant,"Peppers, Chili",NaN,Virus,NaN,Suspected,3,NaN,0.0
10,1998,January,Colorado,Grocery Store,NaN,NaN,Virus,NaN,Suspected,8,NaN,NaN
11,1998,January,Colorado,Restaurant,NaN,NaN,Virus,NaN,Suspected,28,NaN,0.0
12,1998,January,Colorado,Private Home/Residence,NaN,NaN,Virus,NaN,Suspected,10,NaN,NaN
13,1998,January,Florida,Restaurant,Chicken Salad,NaN,NaN,NaN,NaN,2,NaN,NaN
14,1998,January,Florida,Restaurant,"Hot Dog, Kielbasa",NaN,NaN,NaN,NaN,3,0.0,0.0
15,1998,January,Florida,Restaurant,"Ethnic Style, Unspecified",NaN,Clostridium perfringens,NaN,Suspected,3,0.0,0.0
16,1998,January,Florida,Restaurant,Greek Salad,NaN,Norovirus genogroup I,NaN,Suspected,2,NaN,NaN
17,1998,January,Florida,Restaurant,"Ground Beef, Cheeseburger",NaN,Staphylococcus aureus,NaN,Suspected,2,0.0,0.0
18,1998,January,Florida,Restaurant,"Pasta, Unspecified",NaN,Bacillus cereus,NaN,Suspected,2,0.0,0.0
19,1998,January,Florida,Restaurant,"Sauces, Unspecified; Tuna, Unspecified",NaN,Scombroid toxin,NaN,Suspected,2,2.0,0.0
20,1998,January,Florida,Restaurant,"Sandwich, Chicken",NaN,Campylobacter unknown,NaN,Confirmed,3,1.0,0.0
21,1998,January,Florida,Restaurant,"Chicken, Unspecified",NaN,NaN,NaN,NaN,3,0.0,0.0
22,1998,January,Florida,Restaurant,"Chicken, Fried",NaN,Bacillus cereus,NaN,Suspected,5,0.0,0.0
23,1998,January,Florida,Restaurant,"Doughnuts, Unspecified",NaN,NaN,NaN,NaN,3,0.0,0.0
24,1998,January,Florida,Restaurant,"Tomato Sauce, Unspecified",NaN,NaN,NaN,NaN,5,0.0,0.0
25,1998,January,Florida,Restaurant,"Steak, Unspecified",NaN,NaN,NaN,NaN,2,0.0,0.0
26,1998,January,Florida,Restaurant,Unknown Food,NaN,NaN,NaN,NaN,2,0.0,0.0
27,1998,January,Florida,Restaurant,"Chicken, Nuggets/Fingers; French Fries; Soda, ...",NaN,NaN,NaN,NaN,2,1.0,0.0
28,1998,January,Florida,Private Home/Residence,"Turkey, Unspecified",NaN,NaN,NaN,NaN,18,5.0,0.0
29,1998,January,Florida,Restaurant,"Steak, Unspecified",NaN,NaN,NaN,NaN,2,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
19089,2015,December,North Carolina,Catering Service,NaN,NaN,NaN,NaN,NaN,18,0.0,0.0
19090,2015,December,North Dakota,Catering Service,NaN,NaN,Norovirus genogroup II,Unknown,Confirmed,42,0.0,0.0
19091,2015,December,North Dakota,Prison/Jail,NaN,NaN,Clostridium perfringens,NaN,Confirmed,115,0.0,0.0
19092,2015,December,Ohio,Private Home/Residence,Chicken Mole,NaN,Clostridium perfringens,NaN,Suspected,8,0.0,0.0
19093,2015,December,Ohio,Catering Service,NaN,NaN,Norovirus genogroup II,GII_2,Confirmed,8,0.0,0.0
19094,2015,December,Ohio,Hospital,Cupcakes,NaN,Norovirus genogroup II,NaN,Confirmed,170,0.0,0.0
19095,2015,December,Ohio,Restaurant,Macaroni And Cheese,NaN,Bacillus cereus; Staphylococcus aureus,NaN,Suspected; Suspected,2,0.0,0.0
19096,2015,December,Ohio,Restaurant,NaN,NaN,Norovirus,NaN,Suspected,6,0.0,0.0
19097,2015,December,Ohio,Restaurant,NaN,NaN,Clostridium perfringens,NaN,Suspected,2,0.0,0.0
19098,2015,December,Ohio,Restaurant,NaN,NaN,Norovirus,NaN,Suspected,4,0.0,0.0
19099,2015,December,Ohio,Restaurant,Eggs Benedict,NaN,Salmonella enterica,Enteritidis,Confirmed,3,2.0,0.0
19100,2015,December,Ohio,Farm/Dairy,"Milk, Unpasteurized","Milk, Whole Milk Unpasteurized",Campylobacter jejuni,NaN,Confirmed,2,2.0,0.0
19101,2015,December,Oregon,NaN,Eggnog,Egg,Salmonella enterica,Enteritidis,Confirmed,7,0.0,0.0
19102,2015,December,South Carolina,Restaurant,Zucchini,Zucchini,Bacillus cereus,NaN,Suspected,8,0.0,0.0
19103,2015,December,Texas,NaN,NaN,NaN,Shigella sonnei; Campylobacter jejuni,NaN,Suspected; Suspected,7,0.0,0.0
19104,2015,December,Utah,Private Home/Residence,NaN,NaN,Salmonella enterica,Enteritidis,Confirmed,3,0.0,0.0
19105,2015,December,Utah,Private Home/Residence,Meal Replacement Powder,NaN,Salmonella enterica,Virchow,Confirmed,3,1.0,0.0
19106,2015,December,Virginia,Restaurant,NaN,NaN,Norovirus genogroup II,NaN,Suspected,9,0.0,0.0
19107,2015,December,Washington,School/College/University,NaN,NaN,Norovirus unknown,NaN,Suspected,2,0.0,0.0
19108,2015,December,Washington,Restaurant,Foie Gras,NaN,Campylobacter unknown,NaN,Suspected,2,0.0,0.0
19109,2015,December,Washington,Restaurant; Private Home/Residence,NaN,NaN,Norovirus unknown,NaN,Suspected,10,0.0,0.0
19110,2015,December,Washington,Restaurant,NaN,NaN,Norovirus unknown,NaN,Suspected,4,0.0,0.0
19111,2015,December,Wisconsin,Catering Service,"Cookies, Chocolate Chip",NaN,Norovirus genogroup II,GII_4 Untypeable,Confirmed,10,0.0,0.0
19112,2015,December,Wisconsin,Banquet Facility,NaN,NaN,Norovirus genogroup II,GII_2,Confirmed,20,0.0,0.0
19113,2015,December,Wisconsin,Banquet Facility,"Gravy, Pork",NaN,Clostridium perfringens,NaN,Suspected,29,NaN,NaN
19114,2015,December,Wisconsin,Restaurant,NaN,NaN,Norovirus genogroup II,GII_14,Confirmed,4,0.0,0.0
19115,2015,December,Wisconsin,Private Home/Residence,Salsa,NaN,Norovirus genogroup II,GII_2,Confirmed,16,0.0,0.0
19116,2015,December,Wisconsin,Nursing Home/Assisted Living Facility,NaN,NaN,Norovirus genogroup II,GII_17 Kawasaki (2014),Confirmed,43,3.0,0.0
19117,2015,December,Wisconsin,Fast Food Restaurant,NaN,NaN,Norovirus genogroup II,GII_2,Confirmed,5,0.0,0.0
19118,2015,December,Wyoming,NaN,NaN,NaN,NaN,NaN,NaN,3,0.0,0.0

In [85]:
disease_data[disease_data.Food.str.lower().str.contains("pizza")== True].mean()

Year                2003.193220
Illnesses              7.911864
Hospitalizations       0.248677
Fatalities             0.015625
dtype: float64

In [86]:
disease_data[disease_data.Food.str.lower().str.contains("ice")== True].mean()

Year                2004.464689
Illnesses             17.957627
Hospitalizations       0.727928
Fatalities             0.061261
dtype: float64

In [87]:
disease_data[disease_data.Food.str.lower().str.contains("chocolate")== True].mean()

Year                2005.770833
Illnesses             18.562500
Hospitalizations       0.538462
Fatalities             0.000000
dtype: float64

disease_data[disease_data.Food.str.lower().str.contains("chips")== True].mean().Fatalities

In [89]:
disease_data[disease_data.Food.str.lower().str.contains("cheese")== True].mean().Fatalities

0.06338028169014084

In [96]:
junk_foods = pd.DataFrame([('ice', 51),
 ('pizza', 40),
 ('chocolate', 34),
 ('chips', 34),
 ('cheese', 23)], columns={"food", "qnty"})

In [97]:
def get_deseased_count_by_food(food):
    return disease_data[disease_data.Food.str.lower().str.contains(food)== True].mean()[1]

In [98]:
def get_fatalities_by_food(food):
    return disease_data[disease_data.Food.str.lower().str.contains(food)== True].mean().Fatalities

In [99]:
current_list = []
for i in junk_foods.food:
    current_list.append([i, get_deseased_count_by_food(i), get_fatalities_by_food(i)])

In [100]:
new_data = pd.DataFrame(current_list)
new_data.columns = ["food", "diseases", "fatalities"]
new_data

        food   diseases  fatalities
0        ice  17.957627    0.061261
1      pizza   7.911864    0.015625
2  chocolate  18.562500    0.000000
3      chips  17.034483    0.000000
4     cheese  18.918033    0.063380

In [104]:
new_table = pd.concat([junk_foods, new_data], axis = 1)
new_table.index = new_table.food
new_table.drop("food", axis = 1)

                        qnty   diseases  fatalities
(ice, ice)                51  17.957627    0.061261
(pizza, pizza)            40   7.911864    0.015625
(chocolate, chocolate)    34  18.562500    0.000000
(chips, chips)            34  17.034483    0.000000
(cheese, cheese)          23  18.918033    0.063380

In [108]:
new_table.corr()

                qnty  diseases  fatalities    sugars
qnty        1.000000 -0.255770    0.077704  0.051676
diseases   -0.255770  1.000000    0.284191  0.467766
fatalities  0.077704  0.284191    1.000000 -0.392630
sugars      0.051676  0.467766   -0.392630  1.000000

In [107]:
new_table["sugars"] = [12.008958,
2.756942,
31.747232,
8.148497,
4.846845]

In [112]:
cat1 = new_table['sugars']
cat2 = new_table['diseases']

ttest_ind(cat1, cat2)

Ttest_indResult(statistic=-0.7458622918595579, pvalue=0.47709205774932617)

In [116]:
stats.f_oneway(cat1, cat2)

F_onewayResult(statistic=0.5563105584179923, pvalue=0.4770920577493256)

In [118]:
new_table

,food,qnty,food,diseases,fatalities,sugars
"(ice, ice)",ice,51,ice,17.957627,0.061261,12.008958
"(pizza, pizza)",pizza,40,pizza,7.911864,0.015625,2.756942
"(chocolate, chocolate)",chocolate,34,chocolate,18.562500,0.000000,31.747232
"(chips, chips)",chips,34,chips,17.034483,0.000000,8.148497
"(cheese, cheese)",cheese,23,cheese,18.918033,0.063380,4.846845

In [119]:
sugars_rating = pd.crosstab(new_table.diseases, new_table['sugars'])
sugars_rating

sugars     2.756942   4.846845   8.148497   12.008958  31.747232
diseases
7.911864           1          0          0          0          0
17.034483          0          0          1          0          0
17.957627          0          0          0          1          0
18.562500          0          0          0          0          1
18.918033          0          1          0          0          0

In [121]:
chi2, pvalue, dof, expected = st.chi2_contingency(sugars_rating)
pvalue

0.22022064660169877

it is more than 0.05 hoorey